[package]
name = "wifi_clock"
version = "0.1.0"
edition = "2021"

[dependencies]
heapless = "0.8"

cortex-m = {version = "0.7.7", features = ["inline-asm"] }
cortex-m-rt = "*"

embassy-time = { version = "0.3.2", features =  ["defmt-timestamp-uptime"]}
embassy-sync = { version = "0.6.0", features = ["defmt"] }
embassy-executor = { version = "0.6.3", features = ["defmt", "arch-cortex-m", "executor-thread", "executor-interrupt", "defmt", "integrated-timers","task-arena-size-98304"] }
embassy-futures =  { version = "*" }
embassy-net = { version = "0.5.0", features=["proto-ipv4","medium-ethernet","udp","tcp","dhcpv4","defmt"]}
embassy-rp = { version = "0.2.0", features=["unstable-pac", "rp2040", "time-driver", "critical-section-impl"] }

smoltcp={version="0.12.0", default-features=false, features=["proto-ipv4","proto-dhcpv4","socket-tcp","socket-udp","medium-ethernet"]}




defmt = { version = "0.3"}
defmt-rtt = "0.4"
log = { version = "*" }
panic-probe = { version = "*", features = ["print-defmt"] }



futures = { version = "*", default-features = false, features = ["async-await", "cfg-target-has-atomic", "unstable"] }

cyw43={version="0.2.0"}
cyw43-pio = {version="0.2.0" }
pio-proc = "0.2"
pio = "0.2.1"
static_cell = "2"
portable-atomic = { version = "1.5", features = ["critical-section"] }
httparse={version="1.8", default-features=false}
sha1_smol={version="1.0.0"}

embedded-hal-1 = { package = "embedded-hal", version = "1.0" }
embedded-hal-async = "1.0"
embedded-hal-bus = { version = "0.1", features = ["async"] }
[profile.dev-compact]
inherits = "dev"
lto = true
opt-level = 3

[build-dependencies]
blob_loader="*"

[patch.crates-io]
embassy-time = { git="https://github.com/embassy-rs/embassy.git"}
embassy-sync = { git="https://github.com/embassy-rs/embassy.git"}
embassy-rp = { git="https://github.com/embassy-rs/embassy.git"}
embassy-executor = { git="https://github.com/embassy-rs/embassy.git" }
embassy-net = { git="https://github.com/embassy-rs/embassy.git"}
embassy-futures = { git="https://github.com/embassy-rs/embassy.git"}

cyw43={git = "https://github.com/embassy-rs/embassy.git"}
cyw43-pio={git = "https://github.com/embassy-rs/embassy.git"}
blob_loader={git= "https://github.com/fluffware/blob_loader.git"}
